edition = 1
exports = []

[package]
name = "askc-ts"
description = "Ask client"

[package.actr_type]
manufacturer = "askaway1"
name = "Client"

[dependencies]
ask-service = { actr_type = "askaway1+AskService" }

[system.signaling]
url = "wss://actrix1.develenv.com/signaling/ws"

[system.deployment]
realm_id = 2368266035

[system.discovery]
visible = true

[system.webrtc]
force_relay = false
stun_urls = ["stun:actrix1.develenv.com:3478"]
turn_urls = ["turn:actrix1.develenv.com:3478"]

[acl]

[[acl.rules]]
permission = "allow"
types = ["askaway1+AskService"]
