[metadata]
version = 1
generated_at = "2026-02-04T07:19:58.769019+00:00"

[[dependency]]
name = "ask-service"
actr_type = "askaway1+AskService"
fingerprint = "service_semantic:4fce1bae95f2aefdd3773e853ce3c4e2505e5a7704faea3e7de6af286c13be58"
cached_at = "2026-02-04T07:19:58.769017+00:00"

[[dependency.files]]
path = "ask-service/ask.proto"
fingerprint = ""
